apiVersion: v1
kind: Service
metadata:
  labels:
    app: drinks-shop
  name: drinks-shop
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: drinks-shop
  type: NodePort
status:
  loadBalancer: {}
