apiVersion: v1
kind: Service
metadata:
  labels:
    app: drinksapp
  name: drinksapp
spec:
  ports:
  - name: 8085-8085
    port: 8085
    protocol: TCP
    targetPort: 8085
  selector:
    app: drinksapp
  type: ClusterIP
status:
  loadBalancer: {}
